version: "3.9"

services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_NAME=***********
#      - POSTGRES_USER=**********
#      - POSTGRES_PASSWORD=**********
#    networks:
#      - djangonetwork
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    links:
#      - db:db
    networks:
      - djangonetwork
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - EMAIL_PAGE_DOMAIN=${EMAIL_PAGE_DOMAIN}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
#    depends_on:
#      - db
networks:
      djangonetwork:
          driver: bridge