# Generated by Django 4.0.6 on 2022-07-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="author's name")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='book name')),
                ('owner_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='ielts_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='ielts_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='FlowChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('belong_flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_charts', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='TableCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='WholeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_selections', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Not Given', 'Not Given')], max_length=16, null=True)),
                ('belong_true_false', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='true_false', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('head_letter', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=4, null=True, verbose_name='Answer')),
                ('belong_to_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='TablePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=64, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_parts', to='ielts_app.tablecompletion')),
            ],
        ),
        migrations.CreateModel(
            name='TableChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, null=True)),
                ('belong_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_choices', to='ielts_app.tablecompletion')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_completions', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='SentencePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence_completions', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_parts', to='ielts_app.summarycompletion')),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_paragraph_matching', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('a_key', models.CharField(max_length=255, null=True)),
                ('b_key', models.CharField(max_length=255, null=True)),
                ('c_key', models.CharField(max_length=255, null=True)),
                ('d_key', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('belong_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('belong_coll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_sentences', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingHeadingChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_choice', models.CharField(max_length=255)),
                ('belong_tomatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='ielts_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_texts', to='ielts_app.wholelist')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('belong_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_choices', to='ielts_app.wholelist')),
            ],
        ),
        migrations.CreateModel(
            name='GivenPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('belong_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_parts', to='ielts_app.matchingsentence')),
            ],
        ),
        migrations.CreateModel(
            name='GivenKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_letter', models.CharField(max_length=1, null=True)),
                ('key_descrp', models.CharField(max_length=255, null=True)),
                ('belong_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_choices', to='ielts_app.summarycompletion')),
            ],
        ),
        migrations.CreateModel(
            name='FlowChartAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128, verbose_name='answer')),
                ('belong_flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_answers', to='ielts_app.flowchart')),
            ],
        ),
        migrations.CreateModel(
            name='ChoicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_descrp', models.CharField(max_length=255, null=True)),
                ('belong_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_parts', to='ielts_app.matchingsentence')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(choices=[('+', '+'), ('--', '--')], max_length=10, null=True)),
                ('belong_collecton', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_questions', to='ielts_app.collection')),
            ],
        ),
    ]
